version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: fraud-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: frauddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  transaction-service:
    build: ./server
    container_name: transaction-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/frauddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  fraud-service:
    build: ./fraud_service
    container_name: fraud-service
    ports:
      - "8000:8000"

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      TRANSACTION_API_URL: http://transaction-service:8080/api/transactions
      FRAUD_API_URL: http://fraud-service:8000/detect
    depends_on:
      - transaction-service
      - fraud-service
    ports:
      - "4000:4000"

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway

volumes:
  postgres_data:
